### ISSUE TITLE
Dogs are not people

### ISSUE THREAD

**Issue by lthibault** [cachance7/dogsarepeopletoo#1]
**- What is the current behavior?**

`dog == person` evaluates to false

**- If the current behavior is a bug, please provide the steps to reproduce.**

1. Obtain dog
2. Obtain person
3. Assert equality between instance of dog and person

**- What is the expected behavior?**

Repository documentation suggests the result should be `true`.  I worry this may be an inherent design flaw, as it's unclear to me how this could be the case.

**- Please mention your node.js, NPM, Hugo and operating system version.**

Node v10.16.0 (npm v6.14.4)

Hugo v0.70.0

MacOS Catalina v10.15.4 (19E266)

**Comment by cachance7** [comment]
no u

**Comment by cachance7** [comment]
fixed

**Comment by lthibault** [comment]
![image](https://user-images.githubusercontent.com/9452561/82265245-74932f80-995e-11ea-9714-d394d6b2929a.png)
